=== bryanvullo/RunwayRedeclaration/src/main/resources/xml/newAirportSchema.xsd
<?xml version="1.0" encoding="UTF-8" ?>
<xs:schema attributeFormDefault="unqualified" elementFormDefault="qualified"
           targetNamespace="http://www.github.com/bryanvullo/RunwayRedeclaration"
           xmlns:xs="http://www.w3.org/2001/XMLSchema">
    <xs:element name="airports">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="airport" maxOccurs="unbounded" minOccurs="0">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element type="xs:string" name="name"/>
                            <xs:element name="runways" minOccurs="0">
                                <xs:complexType>
                                    <xs:sequence>
                                        <xs:element name="runway" maxOccurs="unbounded" minOccurs="0">
                                            <xs:complexType>
                                                <xs:sequence>
                                                    <xs:element type="xs:string" name="name"/>
                                                    <xs:element type="xs:int" name="tora"/>
                                                    <xs:element type="xs:int" name="toda"/>
                                                    <xs:element type="xs:int" name="asda"/>
                                                    <xs:element type="xs:int" name="lda"/>
                                                    <xs:element type="xs:int" name="clearway"/>
                                                    <xs:element type="xs:int" name="stopway"/>
                                                    <xs:element type="xs:int" name="displacedThreshold"/>
                                                </xs:sequence>
                                            </xs:complexType>
                                        </xs:element>
                                    </xs:sequence>
                                </xs:complexType>
                            </xs:element>
                        </xs:sequence>
                    </xs:complexType>
                </xs:element>
            </xs:sequence>
        </xs:complexType>
    </xs:element>
</xs:schema>

=== bryanvullo/RunwayRedeclaration/src/main/resources/xml/newAirports.xml
<?xml version="1.0" encoding="utf-8" ?>

<airports
        xmlns="http://www.github.com/bryanvullo/RunwayRedeclaration"
        xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
        xsi:schemaLocation="http://www.github.com/bryanvullo/RunwayRedeclaration newAirportSchema.xsd">
    <airport>
        <name>Heathrow</name>
        <runways>
            <runway>
                <name>09L</name>
                <tora>3902</tora>
                <toda>3902</toda>
                <asda>3902</asda>
                <lda>3595</lda>
                <clearway>0</clearway>
                <stopway>0</stopway>
                <displacedThreshold>306</displacedThreshold>
            </runway>
            <runway>
                <name>27R</name>
                <tora>3884</tora>
                <toda>3962</toda>
                <asda>3884</asda>
                <lda>3884</lda>
                <clearway>78</clearway>
                <stopway>0</stopway>
                <displacedThreshold>0</displacedThreshold>
            </runway>
            <runway>
                <name>09R</name>
                <tora>3660</tora>
                <toda>3660</toda>
                <asda>3660</asda>
                <lda>3595</lda>
                <clearway>0</clearway>
                <stopway>0</stopway>
                <displacedThreshold>307</displacedThreshold>
            </runway>
            <runway>
                <name>27L</name>
                <tora>3660</tora>
                <toda>3660</toda>
                <asda>3660</asda>
                <lda>3660</lda>
                <clearway>0</clearway>
                <stopway>0</stopway>
                <displacedThreshold>0</displacedThreshold>
            </runway>
        </runways>
    </airport>
    <airport>
        <name>Gatwick</name>
        <runways>
            <runway>
                <name>08L</name>
                <tora>2565</tora>
                <toda>2565</toda>
                <asda>2565</asda>
                <lda>2565</lda>
                <clearway>0</clearway>
                <stopway>0</stopway>
                <displacedThreshold>198</displacedThreshold>
            </runway>
            <runway>
                <name>26R</name>
                <tora>3316</tora>
                <toda>3316</toda>
                <asda>3316</asda>
                <lda>3316</lda>
                <clearway>0</clearway>
                <stopway>0</stopway>
                <displacedThreshold>0</displacedThreshold>
            </runway>
        </runways>
    </airport>
    <airport>
        <name>Manchester</name>
        <runways>
            <runway>
                <name>05L</name>
                <tora>3050</tora>
                <toda>3050</toda>
                <asda>3050</asda>
                <lda>2980</lda>
                <clearway>0</clearway>
                <stopway>0</stopway>
                <displacedThreshold>70</displacedThreshold>
            </runway>
            <runway>
                <name>23R</name>
                <tora>3195</tora>
                <toda>3195</toda>
                <asda>3195</asda>
                <lda>3100</lda>
                <clearway>0</clearway>
                <stopway>0</stopway>
                <displacedThreshold>95</displacedThreshold>
            </runway>
        </runways>
    </airport>
    <airport>
        <name>Birmingham</name>
        <runways>
            <runway>
                <name>15</name>
                <tora>2606</tora>
                <toda>2606</toda>
                <asda>2606</asda>
                <lda>2474</lda>
                <clearway>0</clearway>
                <stopway>0</stopway>
                <displacedThreshold>132</displacedThreshold>
            </runway>
            <runway>
                <name>33</name>
                <tora>2606</tora>
                <toda>2746</toda>
                <asda>2606</asda>
                <lda>2474</lda>
                <clearway>140</clearway>
                <stopway>0</stopway>
                <displacedThreshold>132</displacedThreshold>
            </runway>
        </runways>
    </airport>
</airports>
