=== bryanvullo/RunwayRedeclaration/src/main/resources/xml/obstacleSchema.xsd
<xs:schema attributeFormDefault="unqualified" elementFormDefault="qualified" targetNamespace="http://www.github.com/bryanvullo/RunwayRedeclaration" xmlns:xs="http://www.w3.org/2001/XMLSchema">
    <xs:element name="obstacles">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="obstacle" maxOccurs="unbounded" minOccurs="0">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element type="xs:string" name="obstacleName"/>
                            <xs:element type="xs:float" name="obstacleHeight"/>
                            <xs:element type="xs:float" name="obstacleWidth"/>
                            <xs:element type="xs:float" name="obstacleLength"/>
                            <xs:element type="xs:float" name="obstacleLeftThresholdDistance"/>
                            <xs:element type="xs:float" name="obstacleRightThresholdDistance"/>
                            <xs:element type="xs:float" name="obstacleDistanceFromCentre"/>
                        </xs:sequence>
                    </xs:complexType>
                </xs:element>
            </xs:sequence>
        </xs:complexType>
    </xs:element>
</xs:schema>

=== bryanvullo/RunwayRedeclaration/out/artifacts/RunwayRedeclaration_jar/RunwayRedeclaration/xml/test.xml
<?xml version="1.0" encoding="UTF-8"?>
<obstacles xmlns="http://www.github.com/bryanvullo/RunwayRedeclaration"
           xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
           xsi:schemaLocation="http://www.github.com/bryanvullo/RunwayRedeclaration obstacleSchema.xsd"
>
    <obstacle>
        <obstacleName>Test Obstacle 1</obstacleName>
        <obstacleHeight>5.0</obstacleHeight>
        <obstacleWidth>5.0</obstacleWidth>
        <obstacleLength>15.0</obstacleLength>
        <obstacleLeftThresholdDistance>1.0</obstacleLeftThresholdDistance>
        <obstacleRightThresholdDistance>1.0</obstacleRightThresholdDistance>
        <obstacleDistanceFromCentre>1.0</obstacleDistanceFromCentre>
    </obstacle>
</obstacles>

=== bryanvullo/RunwayRedeclaration/src/main/resources/xml/obstacles.xml
<?xml version="1.0" encoding="UTF-8"?>
<obstacles xmlns="http://www.github.com/bryanvullo/RunwayRedeclaration" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://www.github.com/bryanvullo/RunwayRedeclaration obstacleSchema.xsd">
    <obstacle>
        <obstacleName>Shuttle Bus</obstacleName>
        <obstacleHeight>3.0</obstacleHeight>
        <obstacleWidth>3.0</obstacleWidth>
        <obstacleLength>14.0</obstacleLength>
        <obstacleLeftThresholdDistance>0.0</obstacleLeftThresholdDistance>
        <obstacleRightThresholdDistance>0.0</obstacleRightThresholdDistance>
        <obstacleDistanceFromCentre>0.0</obstacleDistanceFromCentre>
    </obstacle>
    <obstacle>
        <obstacleName>Container</obstacleName>
        <obstacleHeight>3.0</obstacleHeight>
        <obstacleWidth>2.0</obstacleWidth>
        <obstacleLength>12.0</obstacleLength>
        <obstacleLeftThresholdDistance>0.0</obstacleLeftThresholdDistance>
        <obstacleRightThresholdDistance>0.0</obstacleRightThresholdDistance>
        <obstacleDistanceFromCentre>0.0</obstacleDistanceFromCentre>
    </obstacle>
    <obstacle>
        <obstacleName>Boeing 747</obstacleName>
        <obstacleHeight>19.0</obstacleHeight>
        <obstacleWidth>20.0</obstacleWidth>
        <obstacleLength>30.0</obstacleLength>
        <obstacleLeftThresholdDistance>0.0</obstacleLeftThresholdDistance>
        <obstacleRightThresholdDistance>0.0</obstacleRightThresholdDistance>
        <obstacleDistanceFromCentre>0.0</obstacleDistanceFromCentre>
    </obstacle>
    <obstacle>
        <obstacleName>Airbus A380</obstacleName>
        <obstacleHeight>24.0</obstacleHeight>
        <obstacleWidth>20.0</obstacleWidth>
        <obstacleLength>20.0</obstacleLength>
        <obstacleLeftThresholdDistance>0.0</obstacleLeftThresholdDistance>
        <obstacleRightThresholdDistance>0.0</obstacleRightThresholdDistance>
        <obstacleDistanceFromCentre>0.0</obstacleDistanceFromCentre>
    </obstacle>
    <obstacle>
        <obstacleName>Truck</obstacleName>
        <obstacleHeight>3.5</obstacleHeight>
        <obstacleWidth>2.5</obstacleWidth>
        <obstacleLength>6.0</obstacleLength>
        <obstacleLeftThresholdDistance>0.0</obstacleLeftThresholdDistance>
        <obstacleRightThresholdDistance>75.0</obstacleRightThresholdDistance>
        <obstacleDistanceFromCentre>10.0</obstacleDistanceFromCentre>
    </obstacle>
    <obstacle>
        <obstacleName>Southern Obstacle</obstacleName>
        <obstacleHeight>25.0</obstacleHeight>
        <obstacleWidth>5.0</obstacleWidth>
        <obstacleLength>5.0</obstacleLength>
        <obstacleLeftThresholdDistance>500</obstacleLeftThresholdDistance>
        <obstacleRightThresholdDistance>2853</obstacleRightThresholdDistance>
        <obstacleDistanceFromCentre>20.0</obstacleDistanceFromCentre>
    </obstacle>
    <obstacle>
        <obstacleName>Central Obstacle</obstacleName>
        <obstacleHeight>12.0</obstacleHeight>
        <obstacleWidth>5.0</obstacleWidth>
        <obstacleLength>5.0</obstacleLength>
        <obstacleLeftThresholdDistance>-50</obstacleLeftThresholdDistance>
        <obstacleRightThresholdDistance>3646</obstacleRightThresholdDistance>
        <obstacleDistanceFromCentre>0.0</obstacleDistanceFromCentre>
    </obstacle>
    <obstacle>
        <obstacleName>Obstacle near 09R</obstacleName>
        <obstacleHeight>15.0</obstacleHeight>
        <obstacleWidth>5.0</obstacleWidth>
        <obstacleLength>5.0</obstacleLength>
        <obstacleLeftThresholdDistance>150</obstacleLeftThresholdDistance>
        <obstacleRightThresholdDistance>3203</obstacleRightThresholdDistance>
        <obstacleDistanceFromCentre>-60</obstacleDistanceFromCentre> <!-- North is typically negative in aviation contexts -->
    </obstacle>
    <obstacle>
        <obstacleName>Obstacle near 27R</obstacleName>
        <obstacleHeight>20.0</obstacleHeight>
        <obstacleWidth>5.0</obstacleWidth>
        <obstacleLength>5.0</obstacleLength>
        <obstacleLeftThresholdDistance>50</obstacleLeftThresholdDistance>
        <obstacleRightThresholdDistance>3546</obstacleRightThresholdDistance>
        <obstacleDistanceFromCentre>20</obstacleDistanceFromCentre> <!-- Assuming right of centerline to be positive -->
    </obstacle>
</obstacles>
